[package]
name = "udp-discovery"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
once_cell = "1.21.3"
tokio = { version = "1", features = ["full"] }
